[CHERI] Add Bakewell Feature to RISCV Target
[CHERI] Add +xcheri-bakewell option to clang

[CHERI] Fix signals uintptr_t include

[CHERI] Disable CGetType on bakewell

[CHERI] Add new bakewell extensions

[CHERI] Add new bakewell extensions to clang and codegen

[CHERI] Make capability inspection instructions bakewell

[CHERI] Adds checks in purecap mode

[CHERI] Fix bakewell encoding for new instructions cgetsethigh

[CHERI] Implement cmodeswitch instruction

[CHERI] Bakewell Capability Modification Instructions

[CHERI] Bakewell remove pointer arithmetic instructions

[CHERI] Remove CInvoke from bakewell

[CHERI] Remove fast register clearing instructions

[CHERI] Remove CRRL instruction from bakewell

[CHERI] Remove cloadtags from bakewell

[CI/CD] Initial Test

[CI/CD] Fix naming of special ci file

[CI/CD] Remove image and prefer tags

[CI/CD] Simplify variables

[CI/CD] Fix build and source paths

[CI/CD] Fix diretory paths

[CI/CD] Fix typo

[CI/CD] Fix cmake root

[CI/CD] Don't use ninja build tool

[CI/CD] Add multi-threaded build

Add basic dockerfile

Switch to kubernetes es gitlab ci runners

[CI/CD] Limit link jobs to 2

Add more resources to build

Fix memory request

Set 8CPUs and 64GB RAMs for build

Set 16CPUs and 128GB RAMs for build

Save build directory as artifact

Use machine with nvme drives

remove nvme tag

[CI/CD] Move test into build job to prevent artifacts

[CI/CD] Try build everything

[CI/CD] Try quotes for semicolon separated values

[CI/CD] Limit testing to Codegen

[CI/CD] Fix broken tests

[CI/CD] Enable RISCV MC Testing

[CHERI] fix jalr instruction to match bakewell encoding

[CHERI] fix cincoffset instruction to match bakewell encoding

[CHERI] Filter out failing encoding test

[CHERI] Fix cincoffset/imm to match bakewell encoding

[CHERI] Fix CI by filtering out breaking tests

[CHERI] Implement CSetBoundsImm with scaling bit

[CHERI] Remove unused struct

[CHERI] Final cleanup and and const

[CHERI] Fix cheri matching and mnemonic

[CHERI] Fix mir test

[CHERI] Update encodings to match Bakewell

[CHERI] Fix formatting in tests

[CHERI] Fix csetboundsimm operand parsing

[CHERI] Add bakewell Zcheri_mode extension

Fix merge conflicts

[CHERI] Update last remaining bakewell encodings

[CHERI] Fix unsupported bakewell builtins

Under Bakewell the __builtin_cheri_seal() builtin has no meaning since we lack an otype & thus __builtin_cheri_seal_entry() is the only builtin that can be used. This PR updates the Sema checking and test to warn when unsupported builtins are used with bakewell.

[CHERI] Implement Mode Switching Assembler/Disassembler

[CHERI] Remove redundant capmode checking

[CHERI] Formatting fixes

[CHERI] Tests cap-mode sections in disassembler

[CHERI] Add separate assertions for printed capmode options

[CHERI][CI] Introduce LLD testing in CI

[CHERI] enable verbose output

[CHERI] Check User

Add gitlab-ci user

Use docker image with gitlab-ci user

[CHERI] Fixup Dockerfile

[CHERI] Remove redundant bakewell flag

[CHERI] Allow cgetaddr pseudo instruction

[CHERI] Fixup tests cgetaddr

[CHERI] Fix extension macro names

[CHERI] Fix RISCV extension macro names

[CHERI] Adds tests for riscv target feature naming

[CHERI] RISCV Cheri Tablegen Cleanup

[CHERI] Enable __builtin_cheri_sealed_get for bakewell
Fix its expansion to avoid PseudoLI

[Cheri] Fix the build of emutls.c for purecap

[CHERI] Fix the build of clear_cache.c for risc-v purecap linux

[CHERI] Rename CSeal to CSealEntry

[CHERI] Fix broken tests

[Morello] Allow llvm.thread.pointer to return a capability
for the purecap ABI.

[CHERI] Generalize test for cheri, and rename

[CHERI] Fixup JALR cheri version mnemonics

[CHERI] Fixup Tests

[CHERI] Fix jalr mnemonics

[CHERI] Update tests to use new mnemonics

[CHERI] Fix lld tests

[CHERI] Fix compiler-rt builtins

[CHERI] Fix compiler-rt changed mnemonics

[CHERI] Enable capability offset get and set for bakewell

[CHERI] Implement RISCV cmv mnemonic

Stephen/call mnemonic

[CHERI] Rebase on cambridge/dev fixes

[CHERI] Implement builtin_cheri_copy_from/to_high for bakewell

[CHERI] Update cmodeswitch mnemonic

[CHERI] update cincoffset mnemonic

[CHERI] Change cret to ret in libunwind

[CHERI] Update remaining instruction mnemonics

[CHERI] Update lc instruction encoding

[CHERI] Update bakewell mnemonics

[CHERI] Update bakewell mnemonics in libunwind

[CHERI] Remove AUIPCC mnemonic

[CHERI] Setup nightly CI pipeline

[CHERI] Fix memory capmode mnemonics

[clang-tidy] Rename the make-confusable-table executable

Rename it to clang-tidy-confusable-chars-gen, to make its role
clearer in a wider context.

In cross builds, the caller might want to provide this tool
externally (to avoid needing to rebuild it in the cross build).
In such a case, having the tool properly namespaced makes its role
clearer.

This matches how the clang-pseudo-gen tool was renamed in
a43fef05d4fae32f02365c7b8fef2aa631d23628 / D126725.

Differential Revision: https://reviews.llvm.org/D129798

[clang-tidy] Add CLANG_TIDY_CONFUSABLE_CHARS_GEN cmake cache variable to avoid building when cross compiling

This is similar to the LLVM_TABLEGEN, CLANG_TABLEGEN and
CLANG_PSEUDO_GEN cmake cache variables.

Differential Revision: https://reviews.llvm.org/D129799

[CHERI] Implement CSRRW instructions for bakewell

[CHERI] CBLD & SCSS should not use DDC

[CHERI] Implement CSRRW/C/S aliases

[CHERI][NFC] Start cheri-riscv backend refactor

[CHERI] Refactor capability inspection instructions for bakewell

[CHERI] Implement CHERI-Generic Tests with bakewell invocation

[CHERI] Support llvm.cheri.ddc.get on purecap, iff zCheriLegacy is supported

[CHERI] Fix fld and fsd mnemonics

[CHERI] Rename llc and lgc for bakewell

[CHERI] Make BW package reflect clang version

[CHERI] Fix CSRR alias to use CSRRS instruction

[CHERI] Fix CSR aliases for 0.8 spec

[CHERI] Don't require capmode for csr name parsing

[CHERI] Encode bakewell permission bits

[CHERI] Remove zcheri-mode extension

[CHERI] Catch non-constant-immediate scbnds size operand

[CHERI] Use __weak__ instead of weak, as the latter may be redefined

[CHERI][InstCombine] Add test for 8-byte-capability-sized memcpy

[CHERI][InstCombine] Fix 8-byte capability memcpy inlining

[CHERI] Add test cases for csrrw using integer constant as the csr

[CHERI] Fix error message for using int constant as cheri system register

[CHERI] Tests for bakewell purecap compression instruction support

[CHERI] Replace zcheri-legacy with zcherihybrid

[CHERI] Fix naming of zcheripurecap extension

[CHERI] Fix encoding of bakewell scmode instruction

[CHERI] Use bakewell naming for purecap atomic instructions

[CHERI] Undefine Cambridge permissions endcoding macros for Bakewell

[CHERI] Start to support CHERI zba extension

[CHERI] Fix half-word stack load with zba

[CHERI] Fix stack folding for C_ADD_UW to CLUW

[CHERI] Add some more complex patterns for Zba

[CHERI] Fix JAL aliases to bakewell spec

[CHERI] Bakewell spec change for mnenonics: cflw, cfsw => flw, fsw

[CHERI] Bakewell spec change: remove __CHERI_BW_CAP_PERMISSION_MODE__
acperms no longer reads this bit in its input

[CHERI] Remove definitions from cheriintrin.h that bakewell does not support

[CHERI] Add bakewell implementation for __builtin_cheri_get_type

[CHERI] Reenable llvm.cheri.cap.type.get test for bakewell

[RISCV] Remove AnyReg RegisterClass used by .insn instructions. Use custom operand instead.

The fake register class interferes too much with the autogenerated
register class tables. Especially the fake spill size.

I'm working on .insn support for compressed instructions and adding
AnyRegC broke CodeGen.

[CHERI] [RISCV] Allow capability registers in insn directives

Fixes to enable libunwind and libcxxabi to enable build for rv32 purecap

[CHERI] Refactor Capability Modification Instructions

[CHERI] Add bakewell implementation for __builtin_cheri_get/set_flags

[CHERI] Remove spurious whitespace added in previous commit.

[CHERI] Handle LLVM .gcc_except_table layout for purecap

See CTSRD-CHERI/llvm-project@20df223
for the initial change and CTSRD-CHERI/llvm-project@23f555c
for the current ABI.

 [CHERI] Bring .gcc_except_table for purecap changes closer to morello

[CHERI] Fix Compressed Move

[CHERI] Refactor CSetBounds for bakewell

[CHERI] Refactor CSetBounds for bakewell

[CHERI] Separate Misc Instructions for Bakewell

[llvm-objcopy] Support SREC output format (#75874)

Adds a new output target "srec" to write SREC files from ELF inputs.

https://en.wikipedia.org/wiki/SREC_(file_format)

[CHERI] Add llvm/test/tools to CI config

[llvm-objcopy] Add --gap-fill and --pad-to options (#65815)

`--gap-fill <value>` fills the gaps between sections with a specified
8-bit value, instead of zero.
`--pad-to <address>` pads the output binary up to the specified load
address, using the 8-bit value from `--gap-fill` or zero.

These options are only supported for ELF input and binary output.

[llvm-objcopy] Fix gap-fill/pad-to tests (#75631)

The tests added in PR #65815 fail on Apple buildbot because the `od`
printed addresses have a different number of leading zeroes. Mask
leading zeroes with a regex.
To support the `od` output format on z/OS, add `--ignore-case` to FileCheck.

[CHERI] Remove gp and tp from callee saved register lists.

[CHERI] Refactor CADD/I separate from Cheriv9

Revert "[CHERI] Refactor CADD/I separate from Cheriv9"

This reverts commit a991722a1031651e56bcde3ac1c81285e1f157dc

Reapply "[CHERI] Refactor CADD/I separate from Cheriv9"

This reverts commit 17a538281481282e5e22cf76e7672ba838361250.

[CHERI] Separate more bakewell instructions for v9

[CHERI] Split xcheri from zcheripurecap extension

cheri: Allow explicit symbol size specification

When creating CHERI relocations the linker wants to know the size of
the symbol that it is relocating against. This is used to set the
correct limit for the CHERI capability.

Unfortunately, there is no way to define the symbol size for symbols
that are produced by a linker script. To fix this allow the script
author to define an absolute symol size$<symbol_name> that will be used
by the linker to infer the symbol size if of <symbol_name> if that size
is zero.

This allows us to get rid of most of the CHERI related linker warnings
when building the linux kernel.

cheri: Add the option to disable use of cap relocs

In some special cases it is desirable to avoid the use of cap relocs
in the cap table and use pcc relative addressing instead. Obviously
this possiblity must be used with care as it depends on the pcc having
enough permissions to access everything.

Add a function attribute in capability mode that prevents the use
of the cap table for a function and a command line option that
prevents the use of cap table relocs for an entire file.

This is mainly intended for early startup code written in C that must
run before cap relocs are resolved.

[CHERI] Adds tests for nocaprelocs

[CHERI] Add NoCapRelocs attribute to bitcode

[CHERI] Fix tests after rebase

[libunwind] #include stddef.h

ptraddr_t is defined in stddef.h. Without this compilation fails:
In file included from llvm-project-source-15.0.0-r0/git/libunwind/src/UnwindLevel1-gcc-ext.c:19:
llvm-project-source-15.0.0-r0/git/libunwind/src/config.h:198:3: error: use of undeclared identifier 'ptraddr_t'
  ptraddr_t addr = (ptraddr_t)value;

[CHERI] Enable all testing

[CHERI] Fix libunwind